using IBM.Data.Informix;
using PedidoTela.Entidades.Logica;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PedidoTela.Data.Acceso
{
    public class D_DisponibleParaReserva
    {
    
        private readonly string consulta = "select desc_progra as disenadora, nume_pedido, codi_item referencia, trim(desc_item) as nombre_tela, codi_color, desc_color, anch_trazo, desc_talla " +
                           " , sald_line-nvl(separado,0) disponible " +
                           " from( " +
                           " select comorpro.nume_pedido, comorpro.codi_item, codorpro.codi_color, desc_color, codorpro.codi_subcolor, desc_subcolor, codorpro.anch_trazo, cant_pedido, DECODE((Select nmro_pddo FROM compdcmp WHERE comorpro.nume_pedido= compdcmp.nmro_pddo),null,'PENDIENTE','COMPLETO') as estado,        (select corpedes.cntdad_rcbda from corpedes where codorpro.nume_pedido = corpedes.nmro_pddo and corpedes.codi_color=codorpro.codi_color and corpedes.codi_subcolor=codorpro.codi_subcolor and codorpro.desc_talla=corpedes.desc_talla) as Recibido,     (select corpedes.fcha_cmplto from corpedes where codorpro.nume_pedido = corpedes.nmro_pddo and corpedes.codi_color=codorpro.codi_color and corpedes.codi_subcolor=codorpro.codi_subcolor and codorpro.desc_talla=corpedes.desc_talla) as fecha_recib,      comorpro.codi_progra,comprogr.desc_progra,     trim(items.desc_item) as desc_item,     DECODE((select fn_tipopedido(comorpro.nume_pedido) from desc_color),'I','INTERNO','EXTERNO') as tipo_tela,     sum(inmsatel.sald_line) AS sald_line,     (SELECT sum(mts_consumo)  FROM comtaord  WHERE estado = 'SE' and comtaord.nume_pedido = comorpro.nume_pedido and comtaord.codi_color = codorpro.codi_color and comtaord.codi_subcolor = codorpro.codi_subcolor) as separado,     trim(comorpro.codi_linea) || '-' || cfc_e_lineas.desc_linea as desc_linea,     comorpro.idmundo || '-' || cfc_e_mundo.desc_mundo as desc_mundo,     codorpro.desc_talla,     coremtop.muest_pddo,     coremtop.anio,     DECODE(comorpro.linea_moda,1,'LINEA', DECODE(comorpro.linea_moda,2,'MODA','OTRO'))  as linea_moda,     DECODE(tipo_tela,null,'', DECODE(tipo_tela,'T','PUNTO', DECODE(tipo_tela,'P','PLANO',''))) as tejido,     comorpro.tipo_color,     DECODE(inmcompo.desc_compo2,null, inmcompo.desc_compo1, trim(inmcompo.desc_compo1) || ' ' || trim(inmcompo.desc_compo2)) as composicion,     comorpro.fech_pedido,      'MANUFACTURAS ELIOT' as nomb_provee,     trim(DECODE(comorpro.obs2_pedido,null, trim(comorpro.obs1_pedido), DECODE(trim(comorpro.obs2_pedido),'', trim(comorpro.obs1_pedido), trim(comorpro.obs1_pedido) || ' ' || trim(comorpro.obs2_pedido)))) as observacion,     fn_informetelasconsumos_preciolineal(comorpro.nume_pedido, codorpro.codi_color, codorpro.codi_subcolor, 'I', comorpro.codi_item, to_char(comorpro.fech_pedido,'%iY-%m-%d')) as precio,     fn_informetelasconsumos_preciocuadrado(comorpro.nume_pedido, codorpro.codi_color, codorpro.codi_subcolor, 'I', comorpro.codi_item, to_char(comorpro.fech_pedido,'%iY-%m-%d')) as precio_cuadrado,     codorpro.largo,     DECODE(comorpro.control,null,'ACTIVO', DECODE(comorpro.control,'','ACTIVO', DECODE(comorpro.control,'','ACTIVO', DECODE(comorpro.control,'M','ACTIVO', DECODE(comorpro.control,'X','ANULADO', DECODE(comorpro.control,'S','ACTIVO','')))))) as estado_pedido " +
                           " from comorpro,codorpro,inmterot,inmsatel,inmcolor,inmsubco,comprogr, items, outer cfc_e_lineas, outer cfc_e_mundo, outer coremtop, outer inmcompo " +
                           " where comorpro.nume_pedido=codorpro.nume_pedido and inmterot.nume_pedido = codorpro.nume_pedido and inmterot.codi_color = codorpro.codi_color and inmterot.codi_subcolor = codorpro.codi_subcolor and inmterot.desc_talla = codorpro.desc_talla and inmterot.nume_pedido = inmsatel.nume_pedido and inmterot.nume_rollo = inmsatel.nume_rollo and inmterot.codi_color = inmcolor.codi_color and inmterot.codi_color = inmsubco.codi_color and inmterot.codi_subcolor = inmsubco.codi_subcolor and comprogr.codi_progra=comorpro.codi_progra and comorpro.codi_item=items.codi_item and cfc_e_lineas.codi_linea = comorpro.codi_linea and cfc_e_mundo.idmundo = comorpro.idmundo and coremtop.nume_pedido = comorpro.nume_pedido and comorpro.codi_compo=inmcompo.codi_compo and inmsatel.sald_line >0    and DECODE((Select nmro_pddo FROM compdcmp WHERE comorpro.nume_pedido= compdcmp.nmro_pddo),null,'PENDIENTE','COMPLETO') = 'COMPLETO' " +
                           " and comorpro.codi_progra = ? AND to_char(comorpro.fech_pedido,'%iY-%m-%d') >='2007-01-01' and inmsatel.codi_taller in ('13','64')  and comorpro.codi_item=? and codorpro.codi_color=? " +
                           " group by 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33 " +
                           " union " +
                           " select comorpro.nume_pedido, comorpro.codi_item, codorpro.codi_color, desc_color, codorpro.codi_subcolor, desc_subcolor, codorpro.anch_trazo, cant_pedido, DECODE((Select nmro_pddo FROM compdcmp WHERE comorpro.nume_pedido= compdcmp.nmro_pddo),null,'PENDIENTE','COMPLETO') as estado,  (select corpedes.cntdad_rcbda from corpedes where codorpro.nume_pedido = corpedes.nmro_pddo and corpedes.codi_color=codorpro.codi_color and corpedes.codi_subcolor=codorpro.codi_subcolor and codorpro.desc_talla=corpedes.desc_talla) as Recibido,      (select corpedes.fcha_cmplto from corpedes where codorpro.nume_pedido = corpedes.nmro_pddo and corpedes.codi_color=codorpro.codi_color and corpedes.codi_subcolor=codorpro.codi_subcolor and codorpro.desc_talla=corpedes.desc_talla) as fecha_recib,   comorpro.codi_progra,comprogr.desc_progra,     trim(items.desc_item) as desc_item,      DECODE((select fn_tipopedido(comorpro.nume_pedido) from desc_color),'I','INTERNO','EXTERNO') as tipo_tela,       sum(inmsatel.sald_line) AS sald_line,      (SELECT sum(mts_consumo)  FROM comtaord  WHERE estado = 'SE' and comtaord.nume_pedido = comorpro.nume_pedido and comtaord.codi_color = codorpro.codi_color and comtaord.codi_subcolor = codorpro.codi_subcolor) as separado,       trim(comorpro.codi_linea) || '-' || cfc_e_lineas.desc_linea as desc_linea,     comorpro.idmundo || '-' || cfc_e_mundo.desc_mundo as desc_mundo,     codorpro.desc_talla,     coremtop.muest_pddo,     coremtop.anio,     DECODE(comorpro.linea_moda,1,'LINEA', DECODE(comorpro.linea_moda,2,'MODA','OTRO'))  as linea_moda,     DECODE(tipo_tela,null,'', DECODE(tipo_tela,'T','PUNTO', DECODE(tipo_tela,'P','PLANO',''))) as tejido,     comorpro.tipo_color,     DECODE(inmcompo.desc_compo2,null, inmcompo.desc_compo1, trim(inmcompo.desc_compo1) || ' ' || trim(inmcompo.desc_compo2)) as composicion,     comorpro.fech_pedido,      'MANUFACTURAS ELIOT' as nomb_provee,     trim(DECODE(comorpro.obs2_pedido,null, trim(comorpro.obs1_pedido), DECODE(trim(comorpro.obs2_pedido),'', trim(comorpro.obs1_pedido), trim(comorpro.obs1_pedido) || ' ' || trim(comorpro.obs2_pedido)))) as observacion,   fn_informetelasconsumos_preciolineal(comorpro.nume_pedido, codorpro.codi_color, codorpro.codi_subcolor, 'I', comorpro.codi_item, to_char(comorpro.fech_pedido,'%iY-%m-%d')) as precio,       fn_informetelasconsumos_preciocuadrado(comorpro.nume_pedido, codorpro.codi_color, codorpro.codi_subcolor, 'I', comorpro.codi_item, to_char(comorpro.fech_pedido,'%iY-%m-%d')) as precio_cuadrado,  codorpro.largo,      DECODE(comorpro.control,null,'ACTIVO', DECODE(comorpro.control,'','ACTIVO', DECODE(comorpro.control,'','ACTIVO', DECODE(comorpro.control,'M','ACTIVO', DECODE(comorpro.control,'X','ANULADO', DECODE(comorpro.control,'S','ACTIVO','')))))) as estado_pedido " +
                           " from comorpro inner join codorpro on comorpro.nume_pedido=codorpro.nume_pedido inner join items on comorpro.codi_item= items.codi_item  inner join comprogr on comprogr.codi_progra= comorpro.codi_progra       inner join inmcolor on codorpro.codi_color = inmcolor.codi_color  inner join inmsubco on codorpro.codi_color = inmsubco.codi_color and codorpro.codi_subcolor = inmsubco.codi_subcolor  left outer join inmterot on inmterot.nume_pedido = codorpro.nume_pedido and inmterot.codi_color = codorpro.codi_color and inmterot.codi_subcolor = codorpro.codi_subcolor and inmterot.desc_talla = codorpro.desc_talla      left outer join inmsatel on inmterot.nume_pedido = inmsatel.nume_pedido and inmterot.nume_rollo = inmsatel.nume_rollo and inmsatel.codi_taller in ('13','64') left outer join cfc_e_lineas on cfc_e_lineas.codi_linea = comorpro.codi_linea left outer join  cfc_e_mundo on cfc_e_mundo.idmundo = comorpro.idmundo       left outer join coremtop on coremtop.nume_pedido = comorpro.nume_pedido      left outer join inmcompo on comorpro.codi_compo= inmcompo.codi_compo " +
                           " where DECODE((Select nmro_pddo FROM compdcmp WHERE comorpro.nume_pedido= compdcmp.nmro_pddo),null,'PENDIENTE','COMPLETO') = 'PENDIENTE' " +
                           " and comorpro.codi_progra = ? AND to_char(comorpro.fech_pedido,'%iY-%m-%d') >='2007-01-01' and comorpro.codi_item=? and codorpro.codi_color =? " +
                           " group by 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33 " +
                           " union " +
                           " SELECT ord_compra.nume_pedido, det_compra.codi_item, det_compra.codi_color, desc_color, det_compra.codi_subcolor, desc_subcolor, det_compra.anch_trazo, cant_pedida as cant_pedido, DECODE((Select nmro_pddo FROM compdcmp WHERE ord_compra.nume_pedido= compdcmp.nmro_pddo),null,'PENDIENTE','COMPLETO') as estado,       (select corpedes.cntdad_rcbda from corpedes where ord_compra.nume_pedido = corpedes.nmro_pddo and corpedes.codi_color=det_compra.codi_color and corpedes.codi_subcolor=det_compra.codi_subcolor ) as Recibido,        (select corpedes.fcha_cmplto from corpedes where ord_compra.nume_pedido = corpedes.nmro_pddo and corpedes.codi_color=det_compra.codi_color and corpedes.codi_subcolor=det_compra.codi_subcolor ) as fecha_recib,       ord_compra.codi_progra, desc_progra, desc_item, DECODE((select fn_tipopedido(ord_compra.nume_pedido) from desc_color),'I','INTERNO','EXTERNO') as tipo_tela,       nvl((select sum(inmsatel.sald_line) AS sald_line from inmsatel INNER JOIN inmterot ON ord_compra.nume_pedido = inmterot.nume_pedido and inmterot.codi_color= det_compra.codi_color and inmterot.codi_subcolor= det_compra.codi_subcolor WHERE inmterot.nume_rollo= inmsatel.nume_rollo and inmterot.nume_pedido = ord_compra.nume_pedido and inmsatel.codi_taller in ('13','64')  and inmsatel.sald_line >0 and inmterot.codi_color = det_compra.codi_color and inmterot.codi_subcolor = det_compra.codi_subcolor),0)  AS sald_line,       (SELECT sum(mts_consumo)  FROM comtaord  WHERE ord_compra.nume_orden = det_compra.nume_orden and ord_compra.codi_taller = det_compra.codi_taller and  estado = 'SE' and comtaord.nume_pedido = ord_compra.nume_pedido and  comtaord.codi_color = det_compra.codi_color and comtaord.codi_subcolor = det_compra.codi_subcolor) as separado,       trim(ord_compra.codi_linea) || '-' || cfc_e_lineas.desc_linea as desc_linea,ord_compra.idmundo || '-' || cfc_e_mundo.desc_mundo as desc_mundo,'' as desc_talla,coremtop.muest_pddo,coremtop.anio,DECODE(ord_compra.linea_moda,1,'LINEA', DECODE(ord_compra.linea_moda,2,'MODA','OTRO')) as linea_moda,DECODE(tipo_tela,null,'', DECODE(tipo_tela,'T','PUNTO', DECODE(tipo_tela,'P','PLANO',''))) as tejido,ord_compra.tipo_color,       DECODE(inmcompo.desc_compo2,null, inmcompo.desc_compo1, trim(inmcompo.desc_compo1) || ' ' || trim(inmcompo.desc_compo2)) as composicion, ord_compra.fech_orden as fech_pedido,proveedores.nomb_provee,       trim(ord_compra.observa) as observacion,       fn_informetelasconsumos_preciolineal(ord_compra.nume_pedido, det_compra.codi_color, det_compra.codi_subcolor, 'E', det_compra.codi_item, to_char(ord_compra.fech_orden,'%iY-%m-%d')) as precio,      fn_informetelasconsumos_preciocuadrado(ord_compra.nume_pedido, det_compra.codi_color, det_compra.codi_subcolor, 'E', det_compra.codi_item, to_char(ord_compra.fech_orden,'%iY-%m-%d')) as precio_cuadrado,      0 as largo,       'ACTIVO' as estado_pedido " +
                           " FROM ord_compra INNER JOIN det_compra ON ord_compra.nume_orden=det_compra.nume_orden and  det_compra.codi_taller= ord_compra.codi_taller       INNER JOIN items ON det_compra.codi_item= items.codi_item       INNER JOIN inmcolor ON inmcolor.codi_color= det_compra.codi_color       INNER JOIN inmsubco ON inmsubco.codi_color= det_compra.codi_color AND inmsubco.codi_subcolor= det_compra.codi_subcolor       INNER JOIN proveedores ON ord_compra.codi_provee= proveedores.codi_provee       INNER JOIN comprogr ON comprogr.codi_progra= ord_compra.codi_progra       LEFT OUTER JOIN inmcompo ON ord_compra.codi_compo= inmcompo.codi_compo       left outer join cfc_e_lineas ON cfc_e_lineas.codi_linea = ord_compra.codi_linea       left outer join cfc_e_mundo ON cfc_e_mundo.idmundo = ord_compra.idmundo       LEFT OUTER JOIN coremtop ON coremtop.nume_pedido = ord_compra.nume_pedido " +
                           " WHERE ord_compra.codi_progra =? AND to_char(ord_compra.fech_orden,'%iY-%m-%d') >='2007-01-01' and ord_compra.codi_taller in ('13','64')       AND DECODE((Select nmro_pddo FROM compdcmp WHERE ord_compra.nume_pedido= compdcmp.nmro_pddo),null,'PENDIENTE','COMPLETO') = 'COMPLETO'        AND nvl((select sum(inmsatel.sald_line) AS sald_line from inmsatel INNER JOIN inmterot ON ord_compra.nume_pedido = inmterot.nume_pedido and inmterot.codi_color= det_compra.codi_color and inmterot.codi_subcolor= det_compra.codi_subcolor WHERE inmterot.nume_rollo= inmsatel.nume_rollo and inmterot.nume_pedido = ord_compra.nume_pedido and inmsatel.codi_taller in ('13','64') and inmsatel.sald_line >0 and inmterot.codi_color = det_compra.codi_color and inmterot.codi_subcolor = det_compra.codi_subcolor),0) >0 " +
                           " and det_compra.codi_item=? and det_compra.codi_color=? " +
                           " GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31 " +
                           " UNION " +
                           " SELECT ord_compra.nume_pedido, det_compra.codi_item, det_compra.codi_color, desc_color, det_compra.codi_subcolor, desc_subcolor, det_compra.anch_trazo, cant_pedida as cant_pedido, DECODE((Select nmro_pddo FROM compdcmp WHERE ord_compra.nume_pedido= compdcmp.nmro_pddo),null,'PENDIENTE','COMPLETO') as estado,       (select corpedes.cntdad_rcbda from corpedes where ord_compra.nume_pedido = corpedes.nmro_pddo and corpedes.codi_color=det_compra.codi_color and corpedes.codi_subcolor=det_compra.codi_subcolor ) as Recibido,        (select corpedes.fcha_cmplto from corpedes where ord_compra.nume_pedido = corpedes.nmro_pddo and corpedes.codi_color=det_compra.codi_color and corpedes.codi_subcolor=det_compra.codi_subcolor ) as fecha_recib,       ord_compra.codi_progra, desc_progra, desc_item, DECODE((select fn_tipopedido(ord_compra.nume_pedido) from desc_color),'I','INTERNO','EXTERNO') as tipo_tela,       nvl((select sum(inmsatel.sald_line) AS sald_line from inmsatel INNER JOIN inmterot ON ord_compra.nume_pedido = inmterot.nume_pedido and inmterot.codi_color= det_compra.codi_color and inmterot.codi_subcolor= det_compra.codi_subcolor WHERE inmterot.nume_rollo= inmsatel.nume_rollo and inmterot.nume_pedido = ord_compra.nume_pedido and inmsatel.codi_taller in ('13','64')  and inmsatel.sald_line >0 and inmterot.codi_color = det_compra.codi_color and inmterot.codi_subcolor = det_compra.codi_subcolor),0)  AS sald_line,       (SELECT sum(mts_consumo)  FROM comtaord  WHERE ord_compra.nume_orden = det_compra.nume_orden and ord_compra.codi_taller = det_compra.codi_taller and  estado = 'SE' and comtaord.nume_pedido = ord_compra.nume_pedido and  comtaord.codi_color = det_compra.codi_color and comtaord.codi_subcolor = det_compra.codi_subcolor) as separado,       trim(ord_compra.codi_linea) || '-' || cfc_e_lineas.desc_linea as desc_linea,ord_compra.idmundo || '-' || cfc_e_mundo.desc_mundo as desc_mundo,'' as desc_talla,coremtop.muest_pddo,coremtop.anio,DECODE(ord_compra.linea_moda,1,'LINEA', DECODE(ord_compra.linea_moda,2,'MODA','OTRO')) as linea_moda,DECODE(tipo_tela,null,'', DECODE(tipo_tela,'T','PUNTO', DECODE(tipo_tela,'P','PLANO',''))) as tejido,ord_compra.tipo_color,       DECODE(inmcompo.desc_compo2,null, inmcompo.desc_compo1, trim(inmcompo.desc_compo1) || ' ' || trim(inmcompo.desc_compo2)) as composicion, ord_compra.fech_orden as fech_pedido,proveedores.nomb_provee,       trim(ord_compra.observa) as observacion,       fn_informetelasconsumos_preciolineal(ord_compra.nume_pedido, det_compra.codi_color, det_compra.codi_subcolor, 'E', det_compra.codi_item, to_char(ord_compra.fech_orden,'%iY-%m-%d')) as precio,      fn_informetelasconsumos_preciocuadrado(ord_compra.nume_pedido, det_compra.codi_color, det_compra.codi_subcolor, 'E', det_compra.codi_item, to_char(ord_compra.fech_orden,'%iY-%m-%d')) as precio_cuadrado,      0 as largo,       'ACTIVO' as estado_pedido " +
                           " FROM ord_compra INNER JOIN det_compra ON ord_compra.nume_orden=det_compra.nume_orden and  det_compra.codi_taller= ord_compra.codi_taller       INNER JOIN items ON det_compra.codi_item= items.codi_item       INNER JOIN inmcolor ON inmcolor.codi_color= det_compra.codi_color       INNER JOIN inmsubco ON inmsubco.codi_color= det_compra.codi_color AND inmsubco.codi_subcolor= det_compra.codi_subcolor       INNER JOIN proveedores ON ord_compra.codi_provee= proveedores.codi_provee       INNER JOIN comprogr ON comprogr.codi_progra= ord_compra.codi_progra       LEFT OUTER JOIN inmcompo ON ord_compra.codi_compo= inmcompo.codi_compo       left outer join cfc_e_lineas ON cfc_e_lineas.codi_linea = ord_compra.codi_linea       left outer join cfc_e_mundo ON cfc_e_mundo.idmundo = ord_compra.idmundo       LEFT OUTER JOIN coremtop ON coremtop.nume_pedido = ord_compra.nume_pedido " +
                           " WHERE ord_compra.codi_progra =? AND to_char(ord_compra.fech_orden,'%iY-%m-%d') >='2007-01-01' and ord_compra.codi_taller in ('13','64')       AND DECODE((Select nmro_pddo FROM compdcmp WHERE ord_compra.nume_pedido= compdcmp.nmro_pddo),null,'PENDIENTE','COMPLETO') = 'PENDIENTE' " +
                           " and det_compra.codi_item=? and det_compra.codi_color=? " +
                           " GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31 " +
                           " )";

        public DisponibleParaReserva Consultar(int idProgramador, string codigoTela, string CodigoColor)
            {
                DisponibleParaReserva detalleReserva = new DisponibleParaReserva();
               //string[] objId = identificador.Split('-');
                //int idDdisenador = Convert.ToInt32(objId.GetValue(0));
                 
                try
                {
                    using (var con = new clsConexion())
                    {


                    con.Parametros.Add(new IfxParameter("@codi_progra", idProgramador.ToString("D4")));
                    con.Parametros.Add(new IfxParameter("@codi_item", codigoTela));
                    con.Parametros.Add(new IfxParameter("@codi_color", CodigoColor));

                    con.Parametros.Add(new IfxParameter("@codi_progra", idProgramador.ToString("D4")));
                    con.Parametros.Add(new IfxParameter("@codi_item", codigoTela));
                    con.Parametros.Add(new IfxParameter("@codi_color", CodigoColor));

                    con.Parametros.Add(new IfxParameter("@codi_progra", idProgramador.ToString("D4")));
                    con.Parametros.Add(new IfxParameter("@codi_item", codigoTela));
                    con.Parametros.Add(new IfxParameter("@codi_color", CodigoColor));

                    con.Parametros.Add(new IfxParameter("@codi_progra", idProgramador.ToString("D4")));
                    con.Parametros.Add(new IfxParameter("@codi_item", codigoTela));
                    con.Parametros.Add(new IfxParameter("@codi_color", CodigoColor));

                    var datos = con.EjecutarConsulta(consulta);
                        while (datos.Read())
                        {
                            detalleReserva.Disenadora =datos["disenadora"].ToString();
                            detalleReserva.Pedido =(datos["nume_pedido"].ToString().Trim());
                            detalleReserva.CodiTela= datos["referencia"].ToString();
                            detalleReserva.NomTela= datos["nombre_tela"].ToString();
                            detalleReserva.Color= datos["codi_color"].ToString();
                            detalleReserva.DesColor= datos["desc_color"].ToString();
                            detalleReserva.DesTalla= datos["desc_talla"].ToString().Trim();
                            detalleReserva.Disponible =decimal.Parse(datos["disponible"].ToString());
                                            
                        
                    }
                        con.cerrarConexion();
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Error: " + ex.Message);
                }
                return detalleReserva;
        }

    }
}
